spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: hc0832
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8&useSSL=false
    username: root
jpa:
  show-sql: true
